### ISSUE TITLE
Error when running latest HA...

### ISSUE THREAD

**Issue by lokanx** [TekniskSupport/home-assistant-skolmaten#2]
`
Logger: homeassistant.components.sensor
Source: custom_components/skolmaten/sensor.py:107
Integration: Sensor (documentation, issues)
First occurred: 1:28:30 PM (1 occurrences)
Last logged: 1:28:30 PM

skolmaten: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 465, in async_device_update
    await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/skolmaten/sensor.py", line 107, in update
    self._attributes.update({"todaysFood": todaysFood})
UnboundLocalError: local variable 'todaysFood' referenced before assignment
`

**Comment by TekniskSupport** [comment]
Hi,

I was not able to reproduce this on my instance but i'll have another look at it!

**Comment by TekniskSupport** [comment]
the latest release should solve the issue

**Comment by lokanx** [comment]
I think it happen when the school had no data.
